# Builder for the module library (plugin .so/.dylib)
{ lib, common }:

{
  # Build the module library
  build = {
    pkgs,
    src,
    config,
    commonArgs,
    logosSdk,
    moduleDeps ? {},
    externalLibs ? {},
    preConfigure ? "",
    postInstall ? "",
  }:
  let
    pluginFilename = common.getPluginFilename pkgs config.name;
    libExt = common.getLibExtension pkgs;
    
    # Collect include directories from module dependencies
    moduleDepIncludes = lib.concatMapStringsSep "\n" (name:
      let dep = moduleDeps.${name} or null;
      in if dep != null then ''
        if [ -d "${dep}/include" ]; then
          echo "Copying include files from ${name}..."
          cp -r "${dep}/include"/* ./generated_code/ 2>/dev/null || true
        fi
      '' else ""
    ) config.dependencies;
    
    # Copy external libraries to lib/
    externalLibCopies = lib.concatMapStringsSep "\n" (extLib:
      let 
        libInfo = externalLibs.${extLib.name} or null;
      in if libInfo != null then ''
        echo "Copying external library ${extLib.name}..."
        mkdir -p lib
        if [ -d "${libInfo}/lib" ]; then
          cp -r "${libInfo}/lib"/* lib/ 2>/dev/null || true
        fi
        if [ -f "${libInfo}" ]; then
          cp "${libInfo}" lib/ 2>/dev/null || true
        fi
      '' else ""
    ) config.external_libraries;
    
  in pkgs.stdenv.mkDerivation (commonArgs // {
    pname = "${commonArgs.pname}-lib";
    
    inherit src;
    
    preConfigure = ''
      runHook prePreConfigure
      
      # Create generated_code directory for generated files
      mkdir -p ./generated_code
      
      # Copy include files from module dependencies
      ${moduleDepIncludes}
      
      # Copy external libraries
      ${externalLibCopies}
      
      # Run logos-cpp-generator with metadata.json and --general-only flag
      echo "Running logos-cpp-generator..."
      
      # Generate metadata.json if it doesn't exist
      if [ ! -f "metadata.json" ]; then
        echo "Generating metadata.json from config..."
        cat > metadata.json << 'METADATA_EOF'
      ${common.generateMetadataJson config}
      METADATA_EOF
      fi
      
      logos-cpp-generator --metadata metadata.json --general-only --output-dir ./generated_code
      
      # Check what was generated by logos-cpp-generator
      echo "Checking generated files in generated_code:"
      ls -la ./generated_code/ 2>/dev/null || echo "No generated files"
      
      # Create include directory and organize generated files
      if [ -f "./generated_code/core_manager_api.h" ] || [ -f "./generated_code/logos_sdk.h" ]; then
        echo "Creating include directory and moving generated files..."
        mkdir -p ./generated_code/include
        # Move generated header files to include directory
        for file in ./generated_code/*.h; do
          if [ -f "$file" ]; then
            mv "$file" ./generated_code/include/
          fi
        done
        # Also copy generated .cpp files to include directory
        for file in ./generated_code/*.cpp; do
          if [ -f "$file" ]; then
            cp "$file" ./generated_code/include/
          fi
        done
        echo "Generated include directory:"
        ls -la ./generated_code/include/ 2>/dev/null || echo "No include files"
      fi
      
      # Run any custom preConfigure hook
      ${preConfigure}
      
      runHook postPreConfigure
    '';
    
    installPhase = ''
      runHook preInstall
      
      mkdir -p $out/lib
      
      # Find and copy the built plugin library
      if [ -f modules/${config.name}_plugin.dylib ]; then
        cp modules/${config.name}_plugin.dylib $out/lib/
      elif [ -f modules/${config.name}_plugin.so ]; then
        cp modules/${config.name}_plugin.so $out/lib/
      elif [ -f ${config.name}_plugin.dylib ]; then
        cp ${config.name}_plugin.dylib $out/lib/
      elif [ -f ${config.name}_plugin.so ]; then
        cp ${config.name}_plugin.so $out/lib/
      else
        echo "Error: No plugin library file found"
        echo "Searching for any plugin files..."
        find . -name "*_plugin.*" -type f 2>/dev/null || true
        exit 1
      fi
      
      # Copy any external libraries
      if [ -d lib ]; then
        for libfile in lib/*.${libExt} lib/*.so lib/*.dylib; do
          if [ -f "$libfile" ]; then
            cp "$libfile" $out/lib/ 2>/dev/null || true
          fi
        done
      fi
      
      # Fix library paths on macOS
      ${lib.optionalString pkgs.stdenv.hostPlatform.isDarwin ''
        # Fix install name for the plugin
        if [ -f "$out/lib/${config.name}_plugin.dylib" ]; then
          ${pkgs.darwin.cctools}/bin/install_name_tool -id "@rpath/${config.name}_plugin.dylib" "$out/lib/${config.name}_plugin.dylib"
        fi
        
        # Fix references to external libraries
        for lib in $out/lib/*.dylib; do
          if [ -f "$lib" ]; then
            libname=$(basename "$lib")
            ${pkgs.darwin.cctools}/bin/install_name_tool -id "@rpath/$libname" "$lib" 2>/dev/null || true
          fi
        done
      ''}
      
      # Install generated include files
      if [ -d "./generated_code/include" ]; then
        mkdir -p $out/include
        cp -r ./generated_code/include/* $out/include/
        echo "Installed generated include files:"
        ls -la $out/include/ 2>/dev/null || echo "No files"
      fi
      
      # Copy metadata.json
      if [ -f "metadata.json" ]; then
        mkdir -p $out/share
        cp metadata.json $out/share/
      fi
      
      # Run any custom postInstall hook
      ${postInstall}
      
      runHook postInstall
    '';
  });
}
